/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eplat.unicom.control;

import com.atom.core.lang.utils.SwingUtils;
import java.awt.Color;
import java.awt.Dimension;
import java.io.InputStream;
import java.util.List;
import org.apache.commons.io.IOUtils;

/**
 *
 * @author shizihu
 */
public class HelpDialog extends javax.swing.JDialog {

    /**
     * Creates new form HelpDialog
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.lblHelp.setPreferredSize(new Dimension(365, 280));
        this.lblHelp.setText(this.readHelpContent());
        this.lblHelp.setBackground(Color.WHITE);
    }

    /**
     * 读取帮助文档内容
     */
    private String readHelpContent() {
        StringBuilder txt = new StringBuilder(256);
        try {
            InputStream input = this.getClass().getResourceAsStream("/Help.html");
            try {
                List<String> lines = IOUtils.readLines(input);
                for (String line : lines) {
                    txt.append(line);
                }
            } finally {
                IOUtils.closeQuietly(input);
            }
        } catch (Exception e) {
            SwingUtils.alert(this, "出错提示", "读取帮助&说明文档内容异常：" + e.getMessage());
        }

        return txt.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("帮助&说明");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lblHelp.setBackground(new java.awt.Color(255, 255, 255));
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHelp.setText("<html>支<b>付</b>宝</html>");
        lblHelp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(lblHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHelp;
    // End of variables declaration//GEN-END:variables
}
